// Generated by CoffeeScript 1.10.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    return res.end('Hello world, using nodemon');
  });

  module.exports = app;

}).call(this);
