// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, express, urlencode;

  express = require('express');

  app = express();

  bodyParser = require('body-parser');

  urlencode = bodyParser.urlencoded({
    extended: false
  });

  app.use(express["static"]('public'));

  app.get('/', function(req, res) {
    return res.end('Hello world, using nodemon, livereload');
  });

  app.get('/cities', function(req, res) {
    var cities;
    cities = {
      Beijing: 'Some desc',
      Shanghai: 'Some desc 1',
      SF: 'Some desc'
    };
    return res.json(Object.keys(cities));
  });

  app.post('/cities', urlencode, function(req, res) {
    var newCity;
    newCity = req.body;
    cities[newCity.name] = newCity.description;
    return res.status(200).json(newCity.name);
  });

  module.exports = app;

}).call(this);
