// Generated by CoffeeScript 1.10.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(req, res) {
    return res.end('Hello world, using nodemon, livereload');
  });

  app.get('/cities', function(req, res) {
    var cities;
    cities = ['Beijing', 'Shanghai', 'SF', "NY"];
    return res.json(cities);
  });

  module.exports = app;

}).call(this);
