// Generated by CoffeeScript 1.9.3
(function() {
  var app, request;

  request = require('supertest');

  app = require('./app');

  request(app).get('/').expect(200).end(function(error) {
    if (error) {
      throw error;
    }
    return console.log('Done');
  });

}).call(this);
