// Generated by CoffeeScript 1.10.0
(function() {
  var app, request;

  request = require('supertest');

  app = require('./app');

  describe('Requests to the root path', function() {
    return it('Returns a 200 status code', function() {
      return request(app).get('/').expect(200).end(function(error) {
        if (error) {
          throw error;
        }
        return done();
      });
    });
  });

}).call(this);
